services:
  node:
    network_mode: "host"
    extra_hosts:
        - "host.docker.internal:host-gateway"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ../trustflow-node
      dockerfile: ../trustflow-docker-setup/docker/node/Dockerfile
    ports:
      - "30609:30609"
