services:
  postgres:
    env_file:
      - path: ../trustflow-database/.env
        required: true
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
      - ./docker/volumes/postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/import:/import
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "trustflow"]
      interval: 10s
      timeout: 20s
      retries: 3
      start_period: 5s  
  node:
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #command: /bin/bash
    env_file:
      - path: .env
        required: true
    build:
      context: ../trustflow-node
      dockerfile: ../trustflow-docker-setup/docker/node/Dockerfile
    ports:
      - "30609:30609"
